from .triplet_loss import TripletLoss
from .kl_divergence import KL,SKL
from .symmetric_loss import SymmetricCE
from .focal_loss import FocalLoss,FocalCosineLoss
from .label_smoothing import LabelSmoothingCE
from .hard_mining import HardMining
from .cross_entropy import MultiLabelCategoricalCrossEntropy
from .cross_entropy import SoftTargetCrossEntropy
from .span_loss import SpanLoss